import { useCallback, useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import * as workspaceApi from '../api/workspace.api';

const starterFields = [{ id: 'summary', label: 'Summary', type: 'text', required: true }, { id: 'details', label: 'Details', type: 'textarea', required: false }];

export default function ProjectFormsPage() {
  const { project, role } = useOutletContext(); const [forms, setForms] = useState([]); const [selected, setSelected] = useState(null); const [answers, setAnswers] = useState({}); const [submissions, setSubmissions] = useState([]); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { try { const result = await workspaceApi.listForms(project.id); setForms(result.forms); setSelected((current) => result.forms.find((f) => f.id === current?.id) ?? result.forms[0] ?? null); } catch (e) { setError(e.message); } }, [project.id]); useEffect(() => { load(); }, [load]);
  useEffect(() => { setAnswers({}); setSubmissions([]); if (selected && role !== 'viewer') workspaceApi.listSubmissions(project.id, selected.id).then((r) => setSubmissions(r.submissions)).catch(() => {}); }, [selected, project.id, role]);
  async function create() { try { await workspaceApi.createForm(project.id, { name: `Request form ${forms.length + 1}`, description: 'Collect structured requests from the project team.', fields: starterFields, isActive: true }); await load(); } catch (e) { setError(e.message); } }
  async function submit(event) { event.preventDefault(); try { await workspaceApi.submitForm(project.id, selected.id, answers); setAnswers({}); setMessage('Response submitted successfully.'); if (role !== 'viewer') setSubmissions((await workspaceApi.listSubmissions(project.id, selected.id)).submissions); } catch (e) { setError(e.message); } }
  return <div><div className="view-heading"><div><h2>Forms</h2><p>Collect consistent requests and feedback from your project members.</p></div>{role === 'admin' && <button className="button primary" onClick={create}>＋ Create form</button>}</div>{error && <p className="alert error">{error}</p>}{message && <p className="alert success">{message}</p>}<div className="forms-layout"><aside className="jira-card docs-list"><h3>Project forms</h3>{forms.map((form) => <button className={selected?.id === form.id ? 'active' : ''} key={form.id} onClick={() => setSelected(form)}>☷ <span>{form.name}<small>{form.submission_count} responses</small></span></button>)}</aside>{selected ? <div className="forms-content"><form className="jira-card form-preview" onSubmit={submit}><span className="status-lozenge active">{selected.is_active ? 'Active' : 'Closed'}</span><h2>{selected.name}</h2><p className="muted">{selected.description}</p>{selected.fields.map((field) => <label key={field.id}>{field.label}{field.type === 'textarea' ? <textarea required={field.required} value={answers[field.id] ?? ''} onChange={(e) => setAnswers({ ...answers, [field.id]: e.target.value })}/> : <input required={field.required} value={answers[field.id] ?? ''} onChange={(e) => setAnswers({ ...answers, [field.id]: e.target.value })}/>}</label>)}<button className="button primary" disabled={!selected.is_active}>Submit response</button></form>{role !== 'viewer' && <section className="jira-card"><h3>Responses</h3>{submissions.map((submission) => <div className="submission" key={submission.id}><b>{submission.submitted_by_name}</b><small>{new Date(submission.created_at).toLocaleString()}</small><pre>{JSON.stringify(submission.answers, null, 2)}</pre></div>)}{!submissions.length && <p className="muted">No responses yet.</p>}</section>}</div> : <div className="jira-card empty-state"><span>☷</span><h3>No forms yet</h3></div>}</div></div>;
}
