import { useCallback, useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import * as workspaceApi from '../api/workspace.api';

export default function ProjectDocsPage() {
  const { project, role } = useOutletContext(); const [docs, setDocs] = useState([]); const [selected, setSelected] = useState(null); const [draft, setDraft] = useState({ title: '', content: '' }); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const result = await workspaceApi.listDocs(project.id); setDocs(result.docs); setSelected((current) => result.docs.find((d) => d.id === current?.id) ?? result.docs[0] ?? null); } catch (e) { setError(e.message); } }, [project.id]); useEffect(() => { load(); }, [load]);
  useEffect(() => { setDraft(selected ? { title: selected.title, content: selected.content } : { title: '', content: '' }); }, [selected]);
  async function save(event) { event.preventDefault(); try { if (selected) await workspaceApi.updateDoc(project.id, selected.id, draft); else await workspaceApi.createDoc(project.id, draft); await load(); } catch (e) { setError(e.message); } }
  return <div><div className="view-heading"><div><h2>Project docs</h2><p>Capture decisions, plans, and project knowledge.</p></div>{role !== 'viewer' && <button className="button primary" onClick={() => setSelected(null)}>＋ New doc</button>}</div>{error && <p className="alert error">{error}</p>}<div className="docs-layout"><aside className="jira-card docs-list"><h3>Pages</h3>{docs.map((doc) => <button className={selected?.id === doc.id ? 'active' : ''} key={doc.id} onClick={() => setSelected(doc)}>▤ <span>{doc.title}<small>Updated by {doc.updated_by_name}</small></span></button>)}{!docs.length && <p className="muted">No pages yet.</p>}</aside><form className="jira-card doc-editor" onSubmit={save}><input disabled={role === 'viewer'} required placeholder="Untitled page" value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })}/><textarea disabled={role === 'viewer'} placeholder="Start writing…" value={draft.content} onChange={(e) => setDraft({ ...draft, content: e.target.value })}/>{role !== 'viewer' && <div><button className="button primary">Save page</button>{selected && role === 'admin' && <button type="button" className="button danger" onClick={async () => { await workspaceApi.deleteDoc(project.id, selected.id); setSelected(null); load(); }}>Delete</button>}</div>}</form></div></div>;
}
