import { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, useNavigate, useParams } from 'react-router-dom';
import * as projectApi from '../api/project.api';
import * as settingsApi from '../api/settings.api';
import Sidebar from '../components/layout/Sidebar';
import { useLocale } from '../contexts/LocaleContext';

const personal = [['general','♙','General'],['notifications','♧','Notifications']];
const adminItems = [['system','▣','System'],['apps','▦','Apps'],['spaces','♢','Spaces'],['work-items','▤','Work items']];
const apps = [['development','Development','Branches, commits, builds, and deployments'],['timeline','Timeline','Date-based planning and milestones'],['docs','Docs','Shared Space documentation'],['forms','Forms','Structured intake and submissions']];

export default function SettingsPage() {
  const { section = 'general' } = useParams(); const navigate = useNavigate();
  const { t, setLocale } = useLocale();
  const [spaces,setSpaces]=useState([]); const [preferences,setPreferences]=useState(null); const [system,setSystem]=useState(null); const [query,setQuery]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [collapsed,setCollapsed]=useState(false);
  const isAdmin = spaces.some((space)=>space.project_role==='admin');
  useEffect(()=>{ Promise.all([projectApi.listProjects(),settingsApi.getPreferences()]).then(([p,u])=>{setSpaces(p.projects);setPreferences(u.preferences);}).catch((e)=>setError(e.message)); },[]);
  useEffect(()=>{ if(isAdmin && !system) settingsApi.getSystem().then((r)=>setSystem(r.system)).catch((e)=>setError(e.message)); },[isAdmin,system]);
  useEffect(()=>{ if(adminItems.some(([key])=>key===section) && spaces.length && !isAdmin) navigate('/settings/general',{replace:true}); },[section,spaces,isAdmin,navigate]);
  const visibleSpaces=useMemo(()=>{const term=query.toLowerCase().trim();return term?spaces.filter((s)=>`${s.key} ${s.name}`.toLowerCase().includes(term)):spaces;},[spaces,query]);
  function toggle(){setCollapsed((v)=>!v);} async function savePreferences(data,msg){try{setError('');const result=await settingsApi.updatePreferences(data);setPreferences(result.preferences);if(data.locale) setLocale(result.preferences.locale);setMessage(msg);}catch(e){setError(e.message);}}
  async function saveSystem(data,msg){try{setError('');setSystem((await settingsApi.updateSystem(data)).system);setMessage(msg);}catch(e){setError(e.message);}}
  async function password(event){event.preventDefault();const data=new FormData(event.currentTarget);try{setError('');await settingsApi.changePassword({currentPassword:data.get('currentPassword'),newPassword:data.get('newPassword')});event.currentTarget.reset();setMessage('Password updated.');}catch(e){setError(e.message);}}
  return <div className="workspace"><Sidebar collapsed={collapsed} onToggle={toggle} spaces={spaces}/><div className="workspace-main"><div className="topbar"><Link className="button subtle" to="/">{t('backToTaskflow')}</Link><strong className="topbar-title">{t('settings')}</strong></div><main className="settings-center"><aside className="settings-switcher"><h2>{t('settings')}</h2><small>{t('personal')}</small>{personal.map(([key,icon])=><NavLink key={key} to={`/settings/${key}`}>{icon} {t(key)}</NavLink>)}{isAdmin&&<><small>{t('administration')}</small>{adminItems.map(([key,icon])=><NavLink key={key} to={`/settings/${key}`}>{icon} {t(key === 'work-items' ? 'workItems' : key)}</NavLink>)}</>}</aside><section className="settings-center-main">{error&&<p className="alert error">{error}</p>}{message&&<p className="alert success">{message}</p>}
    {section==='general'&&preferences&&<><h1>{t('generalSettings')}</h1><p className="muted">{t('generalDescription')}</p><div className="settings-card-grid"><form className="panel stack-form" onSubmit={(e)=>{e.preventDefault();const d=new FormData(e.currentTarget);savePreferences({locale:d.get('locale'),timeZone:d.get('timeZone')},t('generalSaved'));}}><h2>{t('regionalPreferences')}</h2><label>{t('language')}<select name="locale" value={preferences.locale} onChange={(e)=>setPreferences({...preferences,locale:e.target.value})}><option value="en">{t('english')}</option><option value="vi">{t('vietnamese')}</option></select></label><label>{t('timeZone')}<select name="timeZone" value={preferences.time_zone} onChange={(e)=>setPreferences({...preferences,time_zone:e.target.value})}><option>UTC</option><option>Asia/Saigon</option><option>Asia/Singapore</option><option>Europe/London</option><option>America/New_York</option></select></label><button className="button primary">{t('savePreferences')}</button></form><form className="panel stack-form" onSubmit={password}><h2>{t('changePassword')}</h2><label>{t('currentPassword')}<input name="currentPassword" type="password" required/></label><label>{t('newPassword')}<input name="newPassword" type="password" minLength="8" maxLength="72" required/></label><button className="button primary">{t('changePasswordButton')}</button></form></div></>}
    {section==='notifications'&&preferences&&<><h1>{t('notificationSettings')}</h1><p className="muted">{t('notificationDescription')}</p><form className="panel preference-list" onSubmit={(e)=>{e.preventDefault();savePreferences({emailNotifications:preferences.email_notifications,inAppNotifications:preferences.in_app_notifications},t('notificationsSaved'));}}><label><div><b>{t('emailNotifications')}</b><small>{t('emailNotificationsDescription')}</small></div><input type="checkbox" checked={preferences.email_notifications} onChange={(e)=>setPreferences({...preferences,email_notifications:e.target.checked})}/></label><label><div><b>{t('inAppNotifications')}</b><small>{t('inAppNotificationsDescription')}</small></div><input type="checkbox" checked={preferences.in_app_notifications} onChange={(e)=>setPreferences({...preferences,in_app_notifications:e.target.checked})}/></label><button className="button primary">{t('saveNotifications')}</button></form></>}
    {section==='system'&&isAdmin&&system&&<><h1>System</h1><p className="muted">Configure defaults for this Taskflow installation.</p><form className="panel stack-form narrow-settings" onSubmit={(e)=>{e.preventDefault();saveSystem({instanceName:system.instance_name,defaultLocale:system.default_locale,defaultTimeZone:system.default_time_zone,emailNotificationsEnabled:system.email_notifications_enabled,inAppNotificationsEnabled:system.in_app_notifications_enabled},'System settings saved.');}}><label>Instance name<input value={system.instance_name} onChange={(e)=>setSystem({...system,instance_name:e.target.value})}/></label><label>Default language<select value={system.default_locale} onChange={(e)=>setSystem({...system,default_locale:e.target.value})}><option value="en">English</option><option value="vi">Tiếng Việt</option></select></label><label>Default time zone<select value={system.default_time_zone} onChange={(e)=>setSystem({...system,default_time_zone:e.target.value})}><option>UTC</option><option>Asia/Saigon</option><option>Asia/Singapore</option><option>Europe/London</option><option>America/New_York</option></select></label><label className="toggle-row">Allow email notifications<input type="checkbox" checked={system.email_notifications_enabled} onChange={(e)=>setSystem({...system,email_notifications_enabled:e.target.checked})}/></label><label className="toggle-row">Allow in-app notifications<input type="checkbox" checked={system.in_app_notifications_enabled} onChange={(e)=>setSystem({...system,in_app_notifications_enabled:e.target.checked})}/></label><button className="button primary">Save system settings</button></form></>}
    {section==='apps'&&isAdmin&&system&&<><h1>Apps</h1><p className="muted">Choose which built-in services Admins may enable for Spaces.</p><form className="app-settings-grid" onSubmit={(e)=>{e.preventDefault();saveSystem({enabledApps:system.enabled_apps},'App settings saved.');}}>{apps.map(([key,name,description])=><label className="panel app-setting-card" key={key}><input type="checkbox" checked={system.enabled_apps.includes(key)} onChange={(e)=>setSystem({...system,enabled_apps:e.target.checked?[...system.enabled_apps,key]:system.enabled_apps.filter((item)=>item!==key)})}/><span><b>{name}</b><small>{description}</small></span></label>)}<button className="button primary">Save app access</button></form></>}
    {section==='spaces'&&isAdmin&&<><div className="section-heading"><div><h1>Manage Spaces</h1><p className="muted">Search every Space, open its settings, or start from a template.</p></div><Link className="button primary" to="/spaces/new">Create Space</Link></div><input className="settings-search" placeholder="Search Spaces" value={query} onChange={(e)=>setQuery(e.target.value)}/><div className="manage-space-list">{visibleSpaces.map((space)=><div className="panel" key={space.id}><span className="project-avatar">{space.key[0]}</span><div><b>{space.name}</b><small>{space.key} · {space.template_key?.replace('_',' ')||'kanban'}</small></div><Link to={`/projects/${space.id}/settings`}>Space settings</Link></div>)}</div></>}
    {section==='work-items'&&isAdmin&&<><h1>Work items</h1><p className="muted">Configure issue types and workflow statuses within each Space.</p><div className="manage-space-list">{spaces.map((space)=><div className="panel" key={space.id}><span className="project-avatar">{space.key[0]}</span><div><b>{space.name}</b><small>Issue types and workflows are isolated to this Space.</small></div><Link to={`/projects/${space.id}/settings`}>Configure</Link></div>)}</div></>}
  </section></main></div></div>;
}
